/* Generated by Yosys 0.29 (git sha1 9c5a60eb201, clang 14.0.3 -fPIC -Os) */

(* src = "alu.sv:1.1-22.10" *)
module alu(a, b, op, r);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _235_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _236_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _237_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _238_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _239_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _240_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _241_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _242_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _243_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _244_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _245_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _246_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _247_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _248_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _249_;
  (* src = "alu.sv:1.25-1.26" *)
  wire _250_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _251_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _252_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _253_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _254_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _255_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _256_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _257_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _258_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _259_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _260_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _261_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _262_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _263_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _264_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _265_;
  (* src = "alu.sv:1.28-1.29" *)
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  (* src = "alu.sv:1.43-1.45" *)
  wire _424_;
  (* src = "alu.sv:1.43-1.45" *)
  wire _425_;
  (* src = "alu.sv:1.43-1.45" *)
  wire _426_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _427_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _428_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _429_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _430_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _431_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _432_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _433_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _434_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _435_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _436_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _437_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _438_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _439_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _440_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _441_;
  (* src = "alu.sv:1.67-1.68" *)
  wire _442_;
  (* src = "alu.sv:1.25-1.26" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "alu.sv:1.28-1.29" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "alu.sv:1.43-1.45" *)
  input [2:0] op;
  wire [2:0] op;
  (* src = "alu.sv:1.67-1.68" *)
  output [15:0] r;
  wire [15:0] r;
  INVX1 _443_ (
    .A(_251_),
    .Y(_379_)
  );
  INVX1 _444_ (
    .A(_425_),
    .Y(_380_)
  );
  INVX1 _445_ (
    .A(_247_),
    .Y(_381_)
  );
  INVX1 _446_ (
    .A(_266_),
    .Y(_382_)
  );
  INVX1 _447_ (
    .A(_236_),
    .Y(_383_)
  );
  INVX1 _448_ (
    .A(_240_),
    .Y(_384_)
  );
  XOR2X1 _449_ (
    .A(_425_),
    .B(_426_),
    .Y(_385_)
  );
  NOR2X1 _450_ (
    .A(_424_),
    .B(_385_),
    .Y(_386_)
  );
  INVX1 _451_ (
    .A(_386_),
    .Y(_387_)
  );
  NOR2X1 _452_ (
    .A(_235_),
    .B(_379_),
    .Y(_388_)
  );
  XNOR2X1 _453_ (
    .A(_235_),
    .B(_251_),
    .Y(_389_)
  );
  NAND2X1 _454_ (
    .A(_424_),
    .B(_380_),
    .Y(_390_)
  );
  NOR2X1 _455_ (
    .A(_426_),
    .B(_390_),
    .Y(_391_)
  );
  AOI22X1 _456_ (
    .A(_424_),
    .B(_385_),
    .C(_391_),
    .D(_235_),
    .Y(_392_)
  );
  OAI21X1 _457_ (
    .A(_387_),
    .B(_389_),
    .C(_392_),
    .Y(_427_)
  );
  NAND2X1 _458_ (
    .A(_425_),
    .B(_426_),
    .Y(_393_)
  );
  NOR2X1 _459_ (
    .A(_424_),
    .B(_393_),
    .Y(_394_)
  );
  OR2X1 _460_ (
    .A(_424_),
    .B(_393_),
    .Y(_395_)
  );
  OAI21X1 _461_ (
    .A(_424_),
    .B(_393_),
    .C(_251_),
    .Y(_396_)
  );
  XOR2X1 _462_ (
    .A(_258_),
    .B(_396_),
    .Y(_397_)
  );
  NAND2X1 _463_ (
    .A(_242_),
    .B(_397_),
    .Y(_398_)
  );
  XNOR2X1 _464_ (
    .A(_242_),
    .B(_397_),
    .Y(_399_)
  );
  AOI21X1 _465_ (
    .A(_388_),
    .B(_399_),
    .C(_387_),
    .Y(_400_)
  );
  OAI21X1 _466_ (
    .A(_388_),
    .B(_399_),
    .C(_400_),
    .Y(_401_)
  );
  AOI22X1 _467_ (
    .A(_380_),
    .B(_426_),
    .C(_242_),
    .D(_391_),
    .Y(_402_)
  );
  NAND2X1 _468_ (
    .A(_401_),
    .B(_402_),
    .Y(_434_)
  );
  NAND2X1 _469_ (
    .A(_243_),
    .B(_391_),
    .Y(_403_)
  );
  OAI21X1 _470_ (
    .A(_388_),
    .B(_399_),
    .C(_398_),
    .Y(_404_)
  );
  OR2X1 _471_ (
    .A(_251_),
    .B(_258_),
    .Y(_405_)
  );
  OAI21X1 _472_ (
    .A(_424_),
    .B(_393_),
    .C(_405_),
    .Y(_406_)
  );
  XOR2X1 _473_ (
    .A(_259_),
    .B(_406_),
    .Y(_407_)
  );
  NOR2X1 _474_ (
    .A(_243_),
    .B(_407_),
    .Y(_408_)
  );
  AND2X1 _475_ (
    .A(_243_),
    .B(_407_),
    .Y(_409_)
  );
  NOR2X1 _476_ (
    .A(_408_),
    .B(_409_),
    .Y(_410_)
  );
  NAND2X1 _477_ (
    .A(_404_),
    .B(_410_),
    .Y(_411_)
  );
  INVX1 _478_ (
    .A(_411_),
    .Y(_412_)
  );
  OAI21X1 _479_ (
    .A(_404_),
    .B(_410_),
    .C(_386_),
    .Y(_413_)
  );
  OAI21X1 _480_ (
    .A(_412_),
    .B(_413_),
    .C(_403_),
    .Y(_435_)
  );
  NAND2X1 _481_ (
    .A(_244_),
    .B(_391_),
    .Y(_414_)
  );
  AOI21X1 _482_ (
    .A(_404_),
    .B(_410_),
    .C(_409_),
    .Y(_415_)
  );
  OR2X1 _483_ (
    .A(_259_),
    .B(_405_),
    .Y(_416_)
  );
  OAI21X1 _484_ (
    .A(_259_),
    .B(_405_),
    .C(_395_),
    .Y(_417_)
  );
  XOR2X1 _485_ (
    .A(_260_),
    .B(_417_),
    .Y(_418_)
  );
  NAND2X1 _486_ (
    .A(_244_),
    .B(_418_),
    .Y(_419_)
  );
  XNOR2X1 _487_ (
    .A(_244_),
    .B(_418_),
    .Y(_420_)
  );
  NAND2X1 _488_ (
    .A(_415_),
    .B(_420_),
    .Y(_421_)
  );
  NOR2X1 _489_ (
    .A(_415_),
    .B(_420_),
    .Y(_422_)
  );
  NAND2X1 _490_ (
    .A(_386_),
    .B(_421_),
    .Y(_423_)
  );
  OAI21X1 _491_ (
    .A(_422_),
    .B(_423_),
    .C(_414_),
    .Y(_436_)
  );
  NAND2X1 _492_ (
    .A(_245_),
    .B(_391_),
    .Y(_267_)
  );
  OAI21X1 _493_ (
    .A(_415_),
    .B(_420_),
    .C(_419_),
    .Y(_268_)
  );
  OR2X1 _494_ (
    .A(_260_),
    .B(_416_),
    .Y(_269_)
  );
  OAI21X1 _495_ (
    .A(_260_),
    .B(_416_),
    .C(_395_),
    .Y(_270_)
  );
  XOR2X1 _496_ (
    .A(_261_),
    .B(_270_),
    .Y(_271_)
  );
  NOR2X1 _497_ (
    .A(_245_),
    .B(_271_),
    .Y(_272_)
  );
  NAND2X1 _498_ (
    .A(_245_),
    .B(_271_),
    .Y(_273_)
  );
  INVX1 _499_ (
    .A(_273_),
    .Y(_274_)
  );
  NOR2X1 _500_ (
    .A(_272_),
    .B(_274_),
    .Y(_275_)
  );
  AND2X1 _501_ (
    .A(_268_),
    .B(_275_),
    .Y(_276_)
  );
  OAI21X1 _502_ (
    .A(_268_),
    .B(_275_),
    .C(_386_),
    .Y(_277_)
  );
  OAI21X1 _503_ (
    .A(_276_),
    .B(_277_),
    .C(_267_),
    .Y(_437_)
  );
  NAND2X1 _504_ (
    .A(_246_),
    .B(_391_),
    .Y(_278_)
  );
  AOI21X1 _505_ (
    .A(_268_),
    .B(_275_),
    .C(_274_),
    .Y(_279_)
  );
  OR2X1 _506_ (
    .A(_261_),
    .B(_269_),
    .Y(_280_)
  );
  OAI21X1 _507_ (
    .A(_261_),
    .B(_269_),
    .C(_395_),
    .Y(_281_)
  );
  XOR2X1 _508_ (
    .A(_262_),
    .B(_281_),
    .Y(_282_)
  );
  NAND2X1 _509_ (
    .A(_246_),
    .B(_282_),
    .Y(_283_)
  );
  XNOR2X1 _510_ (
    .A(_246_),
    .B(_282_),
    .Y(_284_)
  );
  AND2X1 _511_ (
    .A(_279_),
    .B(_284_),
    .Y(_285_)
  );
  OAI21X1 _512_ (
    .A(_279_),
    .B(_284_),
    .C(_386_),
    .Y(_286_)
  );
  OAI21X1 _513_ (
    .A(_285_),
    .B(_286_),
    .C(_278_),
    .Y(_438_)
  );
  OAI21X1 _514_ (
    .A(_279_),
    .B(_284_),
    .C(_283_),
    .Y(_287_)
  );
  OR2X1 _515_ (
    .A(_262_),
    .B(_280_),
    .Y(_288_)
  );
  OAI21X1 _516_ (
    .A(_262_),
    .B(_280_),
    .C(_395_),
    .Y(_289_)
  );
  XNOR2X1 _517_ (
    .A(_263_),
    .B(_289_),
    .Y(_290_)
  );
  NOR2X1 _518_ (
    .A(_381_),
    .B(_290_),
    .Y(_291_)
  );
  XNOR2X1 _519_ (
    .A(_381_),
    .B(_290_),
    .Y(_292_)
  );
  INVX1 _520_ (
    .A(_292_),
    .Y(_293_)
  );
  OR2X1 _521_ (
    .A(_287_),
    .B(_293_),
    .Y(_294_)
  );
  AOI21X1 _522_ (
    .A(_287_),
    .B(_293_),
    .C(_387_),
    .Y(_295_)
  );
  AOI22X1 _523_ (
    .A(_247_),
    .B(_391_),
    .C(_294_),
    .D(_295_),
    .Y(_296_)
  );
  INVX1 _524_ (
    .A(_296_),
    .Y(_439_)
  );
  NAND2X1 _525_ (
    .A(_248_),
    .B(_391_),
    .Y(_297_)
  );
  AOI21X1 _526_ (
    .A(_287_),
    .B(_293_),
    .C(_291_),
    .Y(_298_)
  );
  OR2X1 _527_ (
    .A(_263_),
    .B(_288_),
    .Y(_299_)
  );
  OAI21X1 _528_ (
    .A(_263_),
    .B(_288_),
    .C(_395_),
    .Y(_300_)
  );
  XOR2X1 _529_ (
    .A(_264_),
    .B(_300_),
    .Y(_301_)
  );
  NAND2X1 _530_ (
    .A(_248_),
    .B(_301_),
    .Y(_302_)
  );
  XNOR2X1 _531_ (
    .A(_248_),
    .B(_301_),
    .Y(_303_)
  );
  AND2X1 _532_ (
    .A(_298_),
    .B(_303_),
    .Y(_304_)
  );
  OAI21X1 _533_ (
    .A(_298_),
    .B(_303_),
    .C(_386_),
    .Y(_305_)
  );
  OAI21X1 _534_ (
    .A(_304_),
    .B(_305_),
    .C(_297_),
    .Y(_440_)
  );
  NAND2X1 _535_ (
    .A(_249_),
    .B(_391_),
    .Y(_306_)
  );
  OAI21X1 _536_ (
    .A(_298_),
    .B(_303_),
    .C(_302_),
    .Y(_307_)
  );
  OR2X1 _537_ (
    .A(_264_),
    .B(_299_),
    .Y(_308_)
  );
  OAI21X1 _538_ (
    .A(_264_),
    .B(_299_),
    .C(_395_),
    .Y(_309_)
  );
  XOR2X1 _539_ (
    .A(_265_),
    .B(_309_),
    .Y(_310_)
  );
  NOR2X1 _540_ (
    .A(_249_),
    .B(_310_),
    .Y(_311_)
  );
  AND2X1 _541_ (
    .A(_249_),
    .B(_310_),
    .Y(_312_)
  );
  NOR2X1 _542_ (
    .A(_311_),
    .B(_312_),
    .Y(_313_)
  );
  NAND2X1 _543_ (
    .A(_307_),
    .B(_313_),
    .Y(_314_)
  );
  INVX1 _544_ (
    .A(_314_),
    .Y(_315_)
  );
  OAI21X1 _545_ (
    .A(_307_),
    .B(_313_),
    .C(_386_),
    .Y(_316_)
  );
  OAI21X1 _546_ (
    .A(_315_),
    .B(_316_),
    .C(_306_),
    .Y(_441_)
  );
  NAND2X1 _547_ (
    .A(_250_),
    .B(_391_),
    .Y(_317_)
  );
  AOI21X1 _548_ (
    .A(_307_),
    .B(_313_),
    .C(_312_),
    .Y(_318_)
  );
  NOR2X1 _549_ (
    .A(_265_),
    .B(_308_),
    .Y(_319_)
  );
  NOR2X1 _550_ (
    .A(_394_),
    .B(_319_),
    .Y(_320_)
  );
  XNOR2X1 _551_ (
    .A(_266_),
    .B(_320_),
    .Y(_321_)
  );
  NAND2X1 _552_ (
    .A(_250_),
    .B(_321_),
    .Y(_322_)
  );
  XNOR2X1 _553_ (
    .A(_250_),
    .B(_321_),
    .Y(_323_)
  );
  AND2X1 _554_ (
    .A(_318_),
    .B(_323_),
    .Y(_324_)
  );
  OAI21X1 _555_ (
    .A(_318_),
    .B(_323_),
    .C(_386_),
    .Y(_325_)
  );
  OAI21X1 _556_ (
    .A(_324_),
    .B(_325_),
    .C(_317_),
    .Y(_442_)
  );
  OAI21X1 _557_ (
    .A(_318_),
    .B(_323_),
    .C(_322_),
    .Y(_326_)
  );
  NAND2X1 _558_ (
    .A(_382_),
    .B(_319_),
    .Y(_327_)
  );
  OAI21X1 _559_ (
    .A(_424_),
    .B(_393_),
    .C(_327_),
    .Y(_328_)
  );
  XNOR2X1 _560_ (
    .A(_252_),
    .B(_328_),
    .Y(_329_)
  );
  NOR2X1 _561_ (
    .A(_383_),
    .B(_329_),
    .Y(_330_)
  );
  XNOR2X1 _562_ (
    .A(_383_),
    .B(_329_),
    .Y(_331_)
  );
  INVX1 _563_ (
    .A(_331_),
    .Y(_332_)
  );
  OR2X1 _564_ (
    .A(_326_),
    .B(_332_),
    .Y(_333_)
  );
  AOI21X1 _565_ (
    .A(_326_),
    .B(_332_),
    .C(_387_),
    .Y(_334_)
  );
  AOI22X1 _566_ (
    .A(_236_),
    .B(_391_),
    .C(_333_),
    .D(_334_),
    .Y(_335_)
  );
  INVX1 _567_ (
    .A(_335_),
    .Y(_428_)
  );
  NAND2X1 _568_ (
    .A(_237_),
    .B(_391_),
    .Y(_336_)
  );
  AOI21X1 _569_ (
    .A(_326_),
    .B(_332_),
    .C(_330_),
    .Y(_337_)
  );
  NOR2X1 _570_ (
    .A(_252_),
    .B(_327_),
    .Y(_338_)
  );
  NOR2X1 _571_ (
    .A(_394_),
    .B(_338_),
    .Y(_339_)
  );
  XNOR2X1 _572_ (
    .A(_253_),
    .B(_339_),
    .Y(_340_)
  );
  NAND2X1 _573_ (
    .A(_237_),
    .B(_340_),
    .Y(_341_)
  );
  XNOR2X1 _574_ (
    .A(_237_),
    .B(_340_),
    .Y(_342_)
  );
  AND2X1 _575_ (
    .A(_337_),
    .B(_342_),
    .Y(_343_)
  );
  OAI21X1 _576_ (
    .A(_337_),
    .B(_342_),
    .C(_386_),
    .Y(_344_)
  );
  OAI21X1 _577_ (
    .A(_343_),
    .B(_344_),
    .C(_336_),
    .Y(_429_)
  );
  NAND2X1 _578_ (
    .A(_238_),
    .B(_391_),
    .Y(_345_)
  );
  OAI21X1 _579_ (
    .A(_337_),
    .B(_342_),
    .C(_341_),
    .Y(_346_)
  );
  AOI21X1 _580_ (
    .A(_253_),
    .B(_395_),
    .C(_339_),
    .Y(_347_)
  );
  XOR2X1 _581_ (
    .A(_254_),
    .B(_347_),
    .Y(_348_)
  );
  NOR2X1 _582_ (
    .A(_238_),
    .B(_348_),
    .Y(_349_)
  );
  AND2X1 _583_ (
    .A(_238_),
    .B(_348_),
    .Y(_350_)
  );
  NOR2X1 _584_ (
    .A(_349_),
    .B(_350_),
    .Y(_351_)
  );
  AND2X1 _585_ (
    .A(_346_),
    .B(_351_),
    .Y(_352_)
  );
  OAI21X1 _586_ (
    .A(_346_),
    .B(_351_),
    .C(_386_),
    .Y(_353_)
  );
  OAI21X1 _587_ (
    .A(_352_),
    .B(_353_),
    .C(_345_),
    .Y(_430_)
  );
  NAND2X1 _588_ (
    .A(_239_),
    .B(_391_),
    .Y(_354_)
  );
  AOI21X1 _589_ (
    .A(_346_),
    .B(_351_),
    .C(_350_),
    .Y(_355_)
  );
  OAI21X1 _590_ (
    .A(_424_),
    .B(_393_),
    .C(_254_),
    .Y(_356_)
  );
  NAND2X1 _591_ (
    .A(_347_),
    .B(_356_),
    .Y(_357_)
  );
  XNOR2X1 _592_ (
    .A(_255_),
    .B(_357_),
    .Y(_358_)
  );
  NAND2X1 _593_ (
    .A(_239_),
    .B(_358_),
    .Y(_359_)
  );
  XNOR2X1 _594_ (
    .A(_239_),
    .B(_358_),
    .Y(_360_)
  );
  AND2X1 _595_ (
    .A(_355_),
    .B(_360_),
    .Y(_361_)
  );
  OAI21X1 _596_ (
    .A(_355_),
    .B(_360_),
    .C(_386_),
    .Y(_362_)
  );
  OAI21X1 _597_ (
    .A(_361_),
    .B(_362_),
    .C(_354_),
    .Y(_431_)
  );
  NAND2X1 _598_ (
    .A(_240_),
    .B(_391_),
    .Y(_363_)
  );
  OAI21X1 _599_ (
    .A(_355_),
    .B(_360_),
    .C(_359_),
    .Y(_364_)
  );
  OAI21X1 _600_ (
    .A(_424_),
    .B(_393_),
    .C(_255_),
    .Y(_365_)
  );
  NAND3X1 _601_ (
    .A(_347_),
    .B(_356_),
    .C(_365_),
    .Y(_366_)
  );
  XOR2X1 _602_ (
    .A(_256_),
    .B(_366_),
    .Y(_367_)
  );
  NOR2X1 _603_ (
    .A(_384_),
    .B(_367_),
    .Y(_368_)
  );
  XNOR2X1 _604_ (
    .A(_240_),
    .B(_367_),
    .Y(_369_)
  );
  AND2X1 _605_ (
    .A(_364_),
    .B(_369_),
    .Y(_370_)
  );
  OAI21X1 _606_ (
    .A(_364_),
    .B(_369_),
    .C(_386_),
    .Y(_371_)
  );
  OAI21X1 _607_ (
    .A(_370_),
    .B(_371_),
    .C(_363_),
    .Y(_432_)
  );
  NAND2X1 _608_ (
    .A(_241_),
    .B(_391_),
    .Y(_372_)
  );
  AOI21X1 _609_ (
    .A(_364_),
    .B(_369_),
    .C(_368_),
    .Y(_373_)
  );
  AOI21X1 _610_ (
    .A(_256_),
    .B(_395_),
    .C(_366_),
    .Y(_374_)
  );
  XOR2X1 _611_ (
    .A(_257_),
    .B(_241_),
    .Y(_375_)
  );
  XNOR2X1 _612_ (
    .A(_374_),
    .B(_375_),
    .Y(_376_)
  );
  AND2X1 _613_ (
    .A(_373_),
    .B(_376_),
    .Y(_377_)
  );
  OAI21X1 _614_ (
    .A(_373_),
    .B(_376_),
    .C(_386_),
    .Y(_378_)
  );
  OAI21X1 _615_ (
    .A(_377_),
    .B(_378_),
    .C(_372_),
    .Y(_433_)
  );
  assign _235_ = a[0];
  assign _251_ = b[0];
  assign _424_ = op[0];
  assign _425_ = op[1];
  assign _426_ = op[2];
  assign r[0] = _427_;
  assign _258_ = b[1];
  assign _242_ = a[1];
  assign r[1] = _434_;
  assign _259_ = b[2];
  assign _243_ = a[2];
  assign r[2] = _435_;
  assign _260_ = b[3];
  assign _244_ = a[3];
  assign r[3] = _436_;
  assign _261_ = b[4];
  assign _245_ = a[4];
  assign r[4] = _437_;
  assign _262_ = b[5];
  assign _246_ = a[5];
  assign r[5] = _438_;
  assign _263_ = b[6];
  assign _247_ = a[6];
  assign r[6] = _439_;
  assign _264_ = b[7];
  assign _248_ = a[7];
  assign r[7] = _440_;
  assign _265_ = b[8];
  assign _249_ = a[8];
  assign r[8] = _441_;
  assign _266_ = b[9];
  assign _250_ = a[9];
  assign r[9] = _442_;
  assign _252_ = b[10];
  assign _236_ = a[10];
  assign r[10] = _428_;
  assign _253_ = b[11];
  assign _237_ = a[11];
  assign r[11] = _429_;
  assign _254_ = b[12];
  assign _238_ = a[12];
  assign r[12] = _430_;
  assign _255_ = b[13];
  assign _239_ = a[13];
  assign r[13] = _431_;
  assign _256_ = b[14];
  assign _240_ = a[14];
  assign r[14] = _432_;
  assign _257_ = b[15];
  assign _241_ = a[15];
  assign r[15] = _433_;
endmodule

(* src = "dec.sv:1.1-8.10" *)
module dec(o, aradr, bradr, op, wadr, we, halt);
  (* src = "dec.sv:1.47-1.52" *)
  output [1:0] aradr;
  wire [1:0] aradr;
  (* src = "dec.sv:1.54-1.59" *)
  output [1:0] bradr;
  wire [1:0] bradr;
  (* src = "dec.sv:1.126-1.130" *)
  output halt;
  wire halt;
  (* src = "dec.sv:1.25-1.26" *)
  input [10:0] o;
  wire [10:0] o;
  (* src = "dec.sv:1.80-1.82" *)
  output [2:0] op;
  wire [2:0] op;
  (* src = "dec.sv:1.103-1.107" *)
  output [1:0] wadr;
  wire [1:0] wadr;
  (* src = "dec.sv:1.122-1.124" *)
  output we;
  wire we;
  assign aradr = o[1:0];
  assign bradr = o[3:2];
  assign halt = o[10];
  assign op = o[6:4];
  assign wadr = o[8:7];
  assign we = o[9];
endmodule

(* src = "imem.sv:1.1-39.10" *)
module imem(pc, o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _080_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _081_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _082_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _083_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _084_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _085_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _086_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _087_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _088_;
  (* src = "imem.sv:1.48-1.49" *)
  wire _089_;
  (* src = "imem.sv:1.25-1.27" *)
  wire _090_;
  (* src = "imem.sv:1.25-1.27" *)
  wire _091_;
  (* src = "imem.sv:1.25-1.27" *)
  wire _092_;
  (* src = "imem.sv:1.25-1.27" *)
  wire _093_;
  (* src = "imem.sv:1.25-1.27" *)
  wire _094_;
  (* src = "imem.sv:1.25-1.27" *)
  wire _095_;
  (* src = "imem.sv:1.48-1.49" *)
  output [10:0] o;
  wire [10:0] o;
  (* src = "imem.sv:1.25-1.27" *)
  input [5:0] pc;
  wire [5:0] pc;
  INVX1 _096_ (
    .A(_095_),
    .Y(_051_)
  );
  INVX1 _097_ (
    .A(_090_),
    .Y(_052_)
  );
  INVX1 _098_ (
    .A(_091_),
    .Y(_053_)
  );
  INVX1 _099_ (
    .A(_092_),
    .Y(_054_)
  );
  AND2X1 _100_ (
    .A(_094_),
    .B(_090_),
    .Y(_055_)
  );
  AND2X1 _101_ (
    .A(_092_),
    .B(_093_),
    .Y(_056_)
  );
  AND2X1 _102_ (
    .A(_091_),
    .B(_056_),
    .Y(_057_)
  );
  NAND2X1 _103_ (
    .A(_091_),
    .B(_056_),
    .Y(_058_)
  );
  OR2X1 _104_ (
    .A(_092_),
    .B(_093_),
    .Y(_059_)
  );
  OR2X1 _105_ (
    .A(_091_),
    .B(_059_),
    .Y(_060_)
  );
  NOR2X1 _106_ (
    .A(_094_),
    .B(_052_),
    .Y(_061_)
  );
  OAI21X1 _107_ (
    .A(_091_),
    .B(_059_),
    .C(_061_),
    .Y(_062_)
  );
  NOR2X1 _108_ (
    .A(_094_),
    .B(_093_),
    .Y(_063_)
  );
  NOR3X1 _109_ (
    .A(_094_),
    .B(_092_),
    .C(_093_),
    .Y(_064_)
  );
  AND2X1 _110_ (
    .A(_052_),
    .B(_064_),
    .Y(_065_)
  );
  AOI21X1 _111_ (
    .A(_055_),
    .B(_058_),
    .C(_065_),
    .Y(_066_)
  );
  AOI21X1 _112_ (
    .A(_062_),
    .B(_066_),
    .C(_095_),
    .Y(_080_)
  );
  OAI21X1 _113_ (
    .A(_094_),
    .B(_059_),
    .C(_051_),
    .Y(_067_)
  );
  NOR2X1 _114_ (
    .A(_090_),
    .B(_053_),
    .Y(_068_)
  );
  NAND2X1 _115_ (
    .A(_052_),
    .B(_091_),
    .Y(_069_)
  );
  NOR2X1 _116_ (
    .A(_052_),
    .B(_091_),
    .Y(_070_)
  );
  OAI21X1 _117_ (
    .A(_094_),
    .B(_093_),
    .C(_070_),
    .Y(_071_)
  );
  NOR2X1 _118_ (
    .A(_067_),
    .B(_069_),
    .Y(_083_)
  );
  AOI21X1 _119_ (
    .A(_069_),
    .B(_071_),
    .C(_067_),
    .Y(_082_)
  );
  NOR2X1 _120_ (
    .A(_095_),
    .B(_065_),
    .Y(_072_)
  );
  AOI21X1 _121_ (
    .A(_094_),
    .B(_057_),
    .C(_095_),
    .Y(_089_)
  );
  OAI21X1 _122_ (
    .A(_091_),
    .B(_064_),
    .C(_052_),
    .Y(_073_)
  );
  AND2X1 _123_ (
    .A(_089_),
    .B(_073_),
    .Y(_084_)
  );
  NAND2X1 _124_ (
    .A(_053_),
    .B(_065_),
    .Y(_074_)
  );
  NOR2X1 _125_ (
    .A(_095_),
    .B(_074_),
    .Y(_085_)
  );
  OAI21X1 _126_ (
    .A(_054_),
    .B(_070_),
    .C(_051_),
    .Y(_075_)
  );
  OAI21X1 _127_ (
    .A(_092_),
    .B(_068_),
    .C(_063_),
    .Y(_076_)
  );
  NOR2X1 _128_ (
    .A(_075_),
    .B(_076_),
    .Y(_086_)
  );
  OAI21X1 _129_ (
    .A(_094_),
    .B(_060_),
    .C(_090_),
    .Y(_077_)
  );
  AND2X1 _130_ (
    .A(_072_),
    .B(_077_),
    .Y(_087_)
  );
  AOI21X1 _131_ (
    .A(_055_),
    .B(_056_),
    .C(_053_),
    .Y(_078_)
  );
  AND2X1 _132_ (
    .A(_072_),
    .B(_078_),
    .Y(_088_)
  );
  NAND3X1 _133_ (
    .A(_051_),
    .B(_094_),
    .C(_056_),
    .Y(_079_)
  );
  NOR2X1 _134_ (
    .A(_069_),
    .B(_079_),
    .Y(_081_)
  );
  assign o[3] = 1'h0;
  assign _095_ = pc[5];
  assign _094_ = pc[4];
  assign _090_ = pc[0];
  assign _091_ = pc[1];
  assign _092_ = pc[2];
  assign _093_ = pc[3];
  assign o[0] = _080_;
  assign o[1] = _082_;
  assign o[2] = _083_;
  assign o[4] = _084_;
  assign o[5] = _085_;
  assign o[6] = _086_;
  assign o[7] = _087_;
  assign o[8] = _088_;
  assign o[9] = _089_;
  assign o[10] = _081_;
endmodule

(* src = "pc.sv:1.1-5.10" *)
module pc(halt, pc, clk, rst);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "pc.sv:1.17-1.21" *)
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  (* src = "pc.sv:1.41-1.43" *)
  wire _33_;
  (* src = "pc.sv:1.41-1.43" *)
  wire _34_;
  (* src = "pc.sv:1.41-1.43" *)
  wire _35_;
  (* src = "pc.sv:1.41-1.43" *)
  wire _36_;
  (* src = "pc.sv:1.41-1.43" *)
  wire _37_;
  (* src = "pc.sv:1.41-1.43" *)
  wire _38_;
  (* src = "pc.sv:1.54-1.57" *)
  wire _39_;
  (* force_downto = 32'd1 *)
  (* src = "pc.sv:4.30-4.36|/opt/homebrew/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [5:0] _40_;
  (* force_downto = 32'd1 *)
  (* src = "pc.sv:4.30-4.36|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [5:0] _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  (* src = "pc.sv:1.50-1.53" *)
  input clk;
  wire clk;
  (* src = "pc.sv:1.17-1.21" *)
  input halt;
  wire halt;
  (* src = "pc.sv:1.41-1.43" *)
  output [5:0] pc;
  wire [5:0] pc;
  (* src = "pc.sv:1.54-1.57" *)
  input rst;
  wire rst;
  INVX1 _54_ (
    .A(_38_),
    .Y(_12_)
  );
  INVX1 _55_ (
    .A(_11_),
    .Y(_13_)
  );
  INVX1 _56_ (
    .A(_37_),
    .Y(_14_)
  );
  INVX1 _57_ (
    .A(_36_),
    .Y(_15_)
  );
  INVX1 _58_ (
    .A(_35_),
    .Y(_16_)
  );
  INVX1 _59_ (
    .A(_34_),
    .Y(_17_)
  );
  INVX1 _60_ (
    .A(_33_),
    .Y(_18_)
  );
  INVX1 _61_ (
    .A(_39_),
    .Y(_19_)
  );
  NOR2X1 _62_ (
    .A(_11_),
    .B(_18_),
    .Y(_20_)
  );
  OAI21X1 _63_ (
    .A(_13_),
    .B(_33_),
    .C(_19_),
    .Y(_21_)
  );
  NOR2X1 _64_ (
    .A(_20_),
    .B(_21_),
    .Y(_05_)
  );
  NOR3X1 _65_ (
    .A(_11_),
    .B(_17_),
    .C(_18_),
    .Y(_22_)
  );
  NAND3X1 _66_ (
    .A(_13_),
    .B(_34_),
    .C(_33_),
    .Y(_23_)
  );
  OAI21X1 _67_ (
    .A(_34_),
    .B(_20_),
    .C(_19_),
    .Y(_24_)
  );
  NOR2X1 _68_ (
    .A(_22_),
    .B(_24_),
    .Y(_06_)
  );
  OAI21X1 _69_ (
    .A(_35_),
    .B(_22_),
    .C(_19_),
    .Y(_25_)
  );
  AOI21X1 _70_ (
    .A(_35_),
    .B(_22_),
    .C(_25_),
    .Y(_07_)
  );
  NOR3X1 _71_ (
    .A(_15_),
    .B(_16_),
    .C(_23_),
    .Y(_26_)
  );
  NAND3X1 _72_ (
    .A(_36_),
    .B(_35_),
    .C(_22_),
    .Y(_27_)
  );
  OAI21X1 _73_ (
    .A(_16_),
    .B(_23_),
    .C(_15_),
    .Y(_28_)
  );
  NAND2X1 _74_ (
    .A(_19_),
    .B(_28_),
    .Y(_29_)
  );
  NOR2X1 _75_ (
    .A(_26_),
    .B(_29_),
    .Y(_08_)
  );
  OAI21X1 _76_ (
    .A(_37_),
    .B(_26_),
    .C(_19_),
    .Y(_30_)
  );
  AOI21X1 _77_ (
    .A(_37_),
    .B(_26_),
    .C(_30_),
    .Y(_09_)
  );
  OAI21X1 _78_ (
    .A(_14_),
    .B(_27_),
    .C(_38_),
    .Y(_31_)
  );
  NAND3X1 _79_ (
    .A(_12_),
    .B(_37_),
    .C(_26_),
    .Y(_32_)
  );
  AOI21X1 _80_ (
    .A(_31_),
    .B(_32_),
    .C(_39_),
    .Y(_10_)
  );
  (* src = "pc.sv:2.5-4.37" *)
  DFFPOSX1 _81_ (
    .CLK(clk),
    .D(_43_),
    .Q(pc[0])
  );
  (* src = "pc.sv:2.5-4.37" *)
  DFFPOSX1 _82_ (
    .CLK(clk),
    .D(_45_),
    .Q(pc[1])
  );
  (* src = "pc.sv:2.5-4.37" *)
  DFFPOSX1 _83_ (
    .CLK(clk),
    .D(_47_),
    .Q(pc[2])
  );
  (* src = "pc.sv:2.5-4.37" *)
  DFFPOSX1 _84_ (
    .CLK(clk),
    .D(_49_),
    .Q(pc[3])
  );
  (* src = "pc.sv:2.5-4.37" *)
  DFFPOSX1 _85_ (
    .CLK(clk),
    .D(_51_),
    .Q(pc[4])
  );
  (* src = "pc.sv:2.5-4.37" *)
  DFFPOSX1 _86_ (
    .CLK(clk),
    .D(_53_),
    .Q(pc[5])
  );
  assign _40_[5:1] = pc[5:1];
  assign _41_[0] = _40_[0];
  assign _38_ = pc[5];
  assign _11_ = halt;
  assign _37_ = pc[4];
  assign _36_ = pc[3];
  assign _35_ = pc[2];
  assign _34_ = pc[1];
  assign _33_ = pc[0];
  assign _39_ = rst;
  assign _43_ = _05_;
  assign _45_ = _06_;
  assign _47_ = _07_;
  assign _49_ = _08_;
  assign _51_ = _09_;
  assign _53_ = _10_;
endmodule

(* src = "rega.sv:1.1-8.10" *)
module rega(arad, brad, a, b, we, wad, wd, clk, rst);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _072_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _073_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _074_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _075_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _076_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _077_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _078_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _079_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _080_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _081_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _082_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _083_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _084_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _085_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _086_;
  (* src = "rega.sv:1.62-1.63" *)
  wire _087_;
  (* src = "rega.sv:1.31-1.35" *)
  wire _088_;
  (* src = "rega.sv:1.31-1.35" *)
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _154_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _155_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _156_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _157_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _158_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _159_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _160_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _161_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _162_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _163_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _164_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _165_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _166_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _167_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _168_;
  (* src = "rega.sv:1.64-1.65" *)
  wire _169_;
  (* src = "rega.sv:1.36-1.40" *)
  wire _170_;
  (* src = "rega.sv:1.36-1.40" *)
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  (* src = "rega.sv:1.93-1.96" *)
  wire _387_;
  (* src = "rega.sv:1.93-1.96" *)
  wire _388_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _389_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _390_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _391_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _392_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _393_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _394_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _395_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _396_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _397_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _398_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _399_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _400_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _401_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _402_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _403_;
  (* src = "rega.sv:1.110-1.112" *)
  wire _404_;
  (* src = "rega.sv:1.72-1.74" *)
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  (* src = "rega.sv:1.62-1.63" *)
  output [15:0] a;
  wire [15:0] a;
  (* src = "rega.sv:1.31-1.35" *)
  input [1:0] arad;
  wire [1:0] arad;
  (* src = "rega.sv:1.64-1.65" *)
  output [15:0] b;
  wire [15:0] b;
  (* src = "rega.sv:1.36-1.40" *)
  input [1:0] brad;
  wire [1:0] brad;
  (* src = "rega.sv:1.119-1.122" *)
  input clk;
  wire clk;
  wire [15:0] \regar[0] ;
  wire [15:0] \regar[1] ;
  wire [15:0] \regar[2] ;
  wire [15:0] \regar[3] ;
  (* src = "rega.sv:1.123-1.126" *)
  input rst;
  wire rst;
  (* src = "rega.sv:1.93-1.96" *)
  input [1:0] wad;
  wire [1:0] wad;
  (* src = "rega.sv:1.110-1.112" *)
  input [15:0] wd;
  wire [15:0] wd;
  (* src = "rega.sv:1.72-1.74" *)
  input we;
  wire we;
  INVX1 _470_ (
    .A(_323_),
    .Y(_172_)
  );
  INVX1 _471_ (
    .A(_355_),
    .Y(_173_)
  );
  INVX1 _472_ (
    .A(_330_),
    .Y(_174_)
  );
  INVX1 _473_ (
    .A(_362_),
    .Y(_175_)
  );
  INVX1 _474_ (
    .A(_331_),
    .Y(_176_)
  );
  INVX1 _475_ (
    .A(_363_),
    .Y(_177_)
  );
  INVX1 _476_ (
    .A(_332_),
    .Y(_178_)
  );
  INVX1 _477_ (
    .A(_364_),
    .Y(_179_)
  );
  INVX1 _478_ (
    .A(_333_),
    .Y(_180_)
  );
  INVX1 _479_ (
    .A(_365_),
    .Y(_181_)
  );
  INVX1 _480_ (
    .A(_334_),
    .Y(_182_)
  );
  INVX1 _481_ (
    .A(_366_),
    .Y(_183_)
  );
  INVX1 _482_ (
    .A(_335_),
    .Y(_184_)
  );
  INVX1 _483_ (
    .A(_367_),
    .Y(_185_)
  );
  INVX1 _484_ (
    .A(_336_),
    .Y(_186_)
  );
  INVX1 _485_ (
    .A(_368_),
    .Y(_187_)
  );
  INVX1 _486_ (
    .A(_337_),
    .Y(_188_)
  );
  INVX1 _487_ (
    .A(_369_),
    .Y(_189_)
  );
  INVX1 _488_ (
    .A(_338_),
    .Y(_190_)
  );
  INVX1 _489_ (
    .A(_370_),
    .Y(_191_)
  );
  INVX1 _490_ (
    .A(_324_),
    .Y(_192_)
  );
  INVX1 _491_ (
    .A(_356_),
    .Y(_193_)
  );
  INVX1 _492_ (
    .A(_325_),
    .Y(_194_)
  );
  INVX1 _493_ (
    .A(_357_),
    .Y(_195_)
  );
  INVX1 _494_ (
    .A(_326_),
    .Y(_196_)
  );
  INVX1 _495_ (
    .A(_358_),
    .Y(_197_)
  );
  INVX1 _496_ (
    .A(_327_),
    .Y(_198_)
  );
  INVX1 _497_ (
    .A(_359_),
    .Y(_199_)
  );
  INVX1 _498_ (
    .A(_328_),
    .Y(_200_)
  );
  INVX1 _499_ (
    .A(_360_),
    .Y(_201_)
  );
  INVX1 _500_ (
    .A(_329_),
    .Y(_202_)
  );
  INVX1 _501_ (
    .A(_361_),
    .Y(_203_)
  );
  INVX1 _502_ (
    .A(_388_),
    .Y(_204_)
  );
  INVX1 _503_ (
    .A(_387_),
    .Y(_205_)
  );
  INVX1 _504_ (
    .A(_389_),
    .Y(_206_)
  );
  INVX1 _505_ (
    .A(_396_),
    .Y(_207_)
  );
  INVX1 _506_ (
    .A(_397_),
    .Y(_208_)
  );
  INVX1 _507_ (
    .A(_398_),
    .Y(_209_)
  );
  INVX1 _508_ (
    .A(_399_),
    .Y(_210_)
  );
  INVX1 _509_ (
    .A(_400_),
    .Y(_211_)
  );
  INVX1 _510_ (
    .A(_401_),
    .Y(_212_)
  );
  INVX1 _511_ (
    .A(_402_),
    .Y(_213_)
  );
  INVX1 _512_ (
    .A(_403_),
    .Y(_214_)
  );
  INVX1 _513_ (
    .A(_404_),
    .Y(_215_)
  );
  INVX1 _514_ (
    .A(_390_),
    .Y(_216_)
  );
  INVX1 _515_ (
    .A(_391_),
    .Y(_217_)
  );
  INVX1 _516_ (
    .A(_392_),
    .Y(_218_)
  );
  INVX1 _517_ (
    .A(_393_),
    .Y(_219_)
  );
  INVX1 _518_ (
    .A(_394_),
    .Y(_220_)
  );
  INVX1 _519_ (
    .A(_395_),
    .Y(_221_)
  );
  MUX2X1 _520_ (
    .A(_371_),
    .B(_355_),
    .S(_170_),
    .Y(_222_)
  );
  MUX2X1 _521_ (
    .A(_339_),
    .B(_323_),
    .S(_170_),
    .Y(_223_)
  );
  MUX2X1 _522_ (
    .A(_222_),
    .B(_223_),
    .S(_171_),
    .Y(_154_)
  );
  MUX2X1 _523_ (
    .A(_378_),
    .B(_362_),
    .S(_170_),
    .Y(_224_)
  );
  MUX2X1 _524_ (
    .A(_346_),
    .B(_330_),
    .S(_170_),
    .Y(_225_)
  );
  MUX2X1 _525_ (
    .A(_224_),
    .B(_225_),
    .S(_171_),
    .Y(_161_)
  );
  MUX2X1 _526_ (
    .A(_379_),
    .B(_363_),
    .S(_170_),
    .Y(_226_)
  );
  MUX2X1 _527_ (
    .A(_347_),
    .B(_331_),
    .S(_170_),
    .Y(_227_)
  );
  MUX2X1 _528_ (
    .A(_226_),
    .B(_227_),
    .S(_171_),
    .Y(_162_)
  );
  MUX2X1 _529_ (
    .A(_380_),
    .B(_364_),
    .S(_170_),
    .Y(_228_)
  );
  MUX2X1 _530_ (
    .A(_348_),
    .B(_332_),
    .S(_170_),
    .Y(_229_)
  );
  MUX2X1 _531_ (
    .A(_228_),
    .B(_229_),
    .S(_171_),
    .Y(_163_)
  );
  MUX2X1 _532_ (
    .A(_381_),
    .B(_365_),
    .S(_170_),
    .Y(_230_)
  );
  MUX2X1 _533_ (
    .A(_349_),
    .B(_333_),
    .S(_170_),
    .Y(_231_)
  );
  MUX2X1 _534_ (
    .A(_230_),
    .B(_231_),
    .S(_171_),
    .Y(_164_)
  );
  MUX2X1 _535_ (
    .A(_382_),
    .B(_366_),
    .S(_170_),
    .Y(_232_)
  );
  MUX2X1 _536_ (
    .A(_350_),
    .B(_334_),
    .S(_170_),
    .Y(_233_)
  );
  MUX2X1 _537_ (
    .A(_232_),
    .B(_233_),
    .S(_171_),
    .Y(_165_)
  );
  MUX2X1 _538_ (
    .A(_383_),
    .B(_367_),
    .S(_170_),
    .Y(_234_)
  );
  MUX2X1 _539_ (
    .A(_351_),
    .B(_335_),
    .S(_170_),
    .Y(_235_)
  );
  MUX2X1 _540_ (
    .A(_234_),
    .B(_235_),
    .S(_171_),
    .Y(_166_)
  );
  MUX2X1 _541_ (
    .A(_384_),
    .B(_368_),
    .S(_170_),
    .Y(_236_)
  );
  MUX2X1 _542_ (
    .A(_352_),
    .B(_336_),
    .S(_170_),
    .Y(_237_)
  );
  MUX2X1 _543_ (
    .A(_236_),
    .B(_237_),
    .S(_171_),
    .Y(_167_)
  );
  MUX2X1 _544_ (
    .A(_385_),
    .B(_369_),
    .S(_170_),
    .Y(_238_)
  );
  MUX2X1 _545_ (
    .A(_353_),
    .B(_337_),
    .S(_170_),
    .Y(_239_)
  );
  MUX2X1 _546_ (
    .A(_238_),
    .B(_239_),
    .S(_171_),
    .Y(_168_)
  );
  MUX2X1 _547_ (
    .A(_386_),
    .B(_370_),
    .S(_170_),
    .Y(_240_)
  );
  MUX2X1 _548_ (
    .A(_354_),
    .B(_338_),
    .S(_170_),
    .Y(_241_)
  );
  MUX2X1 _549_ (
    .A(_240_),
    .B(_241_),
    .S(_171_),
    .Y(_169_)
  );
  MUX2X1 _550_ (
    .A(_372_),
    .B(_356_),
    .S(_170_),
    .Y(_242_)
  );
  MUX2X1 _551_ (
    .A(_340_),
    .B(_324_),
    .S(_170_),
    .Y(_243_)
  );
  MUX2X1 _552_ (
    .A(_242_),
    .B(_243_),
    .S(_171_),
    .Y(_155_)
  );
  MUX2X1 _553_ (
    .A(_373_),
    .B(_357_),
    .S(_170_),
    .Y(_244_)
  );
  MUX2X1 _554_ (
    .A(_341_),
    .B(_325_),
    .S(_170_),
    .Y(_245_)
  );
  MUX2X1 _555_ (
    .A(_244_),
    .B(_245_),
    .S(_171_),
    .Y(_156_)
  );
  MUX2X1 _556_ (
    .A(_374_),
    .B(_358_),
    .S(_170_),
    .Y(_246_)
  );
  MUX2X1 _557_ (
    .A(_342_),
    .B(_326_),
    .S(_170_),
    .Y(_247_)
  );
  MUX2X1 _558_ (
    .A(_246_),
    .B(_247_),
    .S(_171_),
    .Y(_157_)
  );
  MUX2X1 _559_ (
    .A(_375_),
    .B(_359_),
    .S(_170_),
    .Y(_248_)
  );
  MUX2X1 _560_ (
    .A(_343_),
    .B(_327_),
    .S(_170_),
    .Y(_249_)
  );
  MUX2X1 _561_ (
    .A(_248_),
    .B(_249_),
    .S(_171_),
    .Y(_158_)
  );
  MUX2X1 _562_ (
    .A(_376_),
    .B(_360_),
    .S(_170_),
    .Y(_250_)
  );
  MUX2X1 _563_ (
    .A(_344_),
    .B(_328_),
    .S(_170_),
    .Y(_251_)
  );
  MUX2X1 _564_ (
    .A(_250_),
    .B(_251_),
    .S(_171_),
    .Y(_159_)
  );
  MUX2X1 _565_ (
    .A(_377_),
    .B(_361_),
    .S(_170_),
    .Y(_252_)
  );
  MUX2X1 _566_ (
    .A(_345_),
    .B(_329_),
    .S(_170_),
    .Y(_253_)
  );
  MUX2X1 _567_ (
    .A(_252_),
    .B(_253_),
    .S(_171_),
    .Y(_160_)
  );
  MUX2X1 _568_ (
    .A(_371_),
    .B(_355_),
    .S(_088_),
    .Y(_254_)
  );
  MUX2X1 _569_ (
    .A(_339_),
    .B(_323_),
    .S(_088_),
    .Y(_255_)
  );
  MUX2X1 _570_ (
    .A(_254_),
    .B(_255_),
    .S(_089_),
    .Y(_072_)
  );
  MUX2X1 _571_ (
    .A(_378_),
    .B(_362_),
    .S(_088_),
    .Y(_256_)
  );
  MUX2X1 _572_ (
    .A(_346_),
    .B(_330_),
    .S(_088_),
    .Y(_257_)
  );
  MUX2X1 _573_ (
    .A(_256_),
    .B(_257_),
    .S(_089_),
    .Y(_079_)
  );
  MUX2X1 _574_ (
    .A(_379_),
    .B(_363_),
    .S(_088_),
    .Y(_258_)
  );
  MUX2X1 _575_ (
    .A(_347_),
    .B(_331_),
    .S(_088_),
    .Y(_259_)
  );
  MUX2X1 _576_ (
    .A(_258_),
    .B(_259_),
    .S(_089_),
    .Y(_080_)
  );
  MUX2X1 _577_ (
    .A(_380_),
    .B(_364_),
    .S(_088_),
    .Y(_260_)
  );
  MUX2X1 _578_ (
    .A(_348_),
    .B(_332_),
    .S(_088_),
    .Y(_261_)
  );
  MUX2X1 _579_ (
    .A(_260_),
    .B(_261_),
    .S(_089_),
    .Y(_081_)
  );
  MUX2X1 _580_ (
    .A(_381_),
    .B(_365_),
    .S(_088_),
    .Y(_262_)
  );
  MUX2X1 _581_ (
    .A(_349_),
    .B(_333_),
    .S(_088_),
    .Y(_263_)
  );
  MUX2X1 _582_ (
    .A(_262_),
    .B(_263_),
    .S(_089_),
    .Y(_082_)
  );
  MUX2X1 _583_ (
    .A(_382_),
    .B(_366_),
    .S(_088_),
    .Y(_264_)
  );
  MUX2X1 _584_ (
    .A(_350_),
    .B(_334_),
    .S(_088_),
    .Y(_265_)
  );
  MUX2X1 _585_ (
    .A(_264_),
    .B(_265_),
    .S(_089_),
    .Y(_083_)
  );
  MUX2X1 _586_ (
    .A(_383_),
    .B(_367_),
    .S(_088_),
    .Y(_266_)
  );
  MUX2X1 _587_ (
    .A(_351_),
    .B(_335_),
    .S(_088_),
    .Y(_267_)
  );
  MUX2X1 _588_ (
    .A(_266_),
    .B(_267_),
    .S(_089_),
    .Y(_084_)
  );
  MUX2X1 _589_ (
    .A(_384_),
    .B(_368_),
    .S(_088_),
    .Y(_268_)
  );
  MUX2X1 _590_ (
    .A(_352_),
    .B(_336_),
    .S(_088_),
    .Y(_269_)
  );
  MUX2X1 _591_ (
    .A(_268_),
    .B(_269_),
    .S(_089_),
    .Y(_085_)
  );
  MUX2X1 _592_ (
    .A(_385_),
    .B(_369_),
    .S(_088_),
    .Y(_270_)
  );
  MUX2X1 _593_ (
    .A(_353_),
    .B(_337_),
    .S(_088_),
    .Y(_271_)
  );
  MUX2X1 _594_ (
    .A(_270_),
    .B(_271_),
    .S(_089_),
    .Y(_086_)
  );
  MUX2X1 _595_ (
    .A(_386_),
    .B(_370_),
    .S(_088_),
    .Y(_272_)
  );
  MUX2X1 _596_ (
    .A(_354_),
    .B(_338_),
    .S(_088_),
    .Y(_273_)
  );
  MUX2X1 _597_ (
    .A(_272_),
    .B(_273_),
    .S(_089_),
    .Y(_087_)
  );
  MUX2X1 _598_ (
    .A(_372_),
    .B(_356_),
    .S(_088_),
    .Y(_274_)
  );
  MUX2X1 _599_ (
    .A(_340_),
    .B(_324_),
    .S(_088_),
    .Y(_275_)
  );
  MUX2X1 _600_ (
    .A(_274_),
    .B(_275_),
    .S(_089_),
    .Y(_073_)
  );
  MUX2X1 _601_ (
    .A(_373_),
    .B(_357_),
    .S(_088_),
    .Y(_276_)
  );
  MUX2X1 _602_ (
    .A(_341_),
    .B(_325_),
    .S(_088_),
    .Y(_277_)
  );
  MUX2X1 _603_ (
    .A(_276_),
    .B(_277_),
    .S(_089_),
    .Y(_074_)
  );
  MUX2X1 _604_ (
    .A(_374_),
    .B(_358_),
    .S(_088_),
    .Y(_278_)
  );
  MUX2X1 _605_ (
    .A(_342_),
    .B(_326_),
    .S(_088_),
    .Y(_279_)
  );
  MUX2X1 _606_ (
    .A(_278_),
    .B(_279_),
    .S(_089_),
    .Y(_075_)
  );
  MUX2X1 _607_ (
    .A(_375_),
    .B(_359_),
    .S(_088_),
    .Y(_280_)
  );
  MUX2X1 _608_ (
    .A(_343_),
    .B(_327_),
    .S(_088_),
    .Y(_281_)
  );
  MUX2X1 _609_ (
    .A(_280_),
    .B(_281_),
    .S(_089_),
    .Y(_076_)
  );
  MUX2X1 _610_ (
    .A(_376_),
    .B(_360_),
    .S(_088_),
    .Y(_282_)
  );
  MUX2X1 _611_ (
    .A(_344_),
    .B(_328_),
    .S(_088_),
    .Y(_283_)
  );
  MUX2X1 _612_ (
    .A(_282_),
    .B(_283_),
    .S(_089_),
    .Y(_077_)
  );
  MUX2X1 _613_ (
    .A(_377_),
    .B(_361_),
    .S(_088_),
    .Y(_284_)
  );
  MUX2X1 _614_ (
    .A(_345_),
    .B(_329_),
    .S(_088_),
    .Y(_285_)
  );
  MUX2X1 _615_ (
    .A(_284_),
    .B(_285_),
    .S(_089_),
    .Y(_078_)
  );
  NAND3X1 _616_ (
    .A(_204_),
    .B(_205_),
    .C(_405_),
    .Y(_286_)
  );
  MUX2X1 _617_ (
    .A(_172_),
    .B(_206_),
    .S(_286_),
    .Y(_090_)
  );
  MUX2X1 _618_ (
    .A(_174_),
    .B(_207_),
    .S(_286_),
    .Y(_091_)
  );
  MUX2X1 _619_ (
    .A(_176_),
    .B(_208_),
    .S(_286_),
    .Y(_092_)
  );
  MUX2X1 _620_ (
    .A(_178_),
    .B(_209_),
    .S(_286_),
    .Y(_093_)
  );
  MUX2X1 _621_ (
    .A(_180_),
    .B(_210_),
    .S(_286_),
    .Y(_094_)
  );
  MUX2X1 _622_ (
    .A(_182_),
    .B(_211_),
    .S(_286_),
    .Y(_095_)
  );
  MUX2X1 _623_ (
    .A(_184_),
    .B(_212_),
    .S(_286_),
    .Y(_096_)
  );
  MUX2X1 _624_ (
    .A(_186_),
    .B(_213_),
    .S(_286_),
    .Y(_097_)
  );
  MUX2X1 _625_ (
    .A(_188_),
    .B(_214_),
    .S(_286_),
    .Y(_098_)
  );
  MUX2X1 _626_ (
    .A(_190_),
    .B(_215_),
    .S(_286_),
    .Y(_099_)
  );
  MUX2X1 _627_ (
    .A(_192_),
    .B(_216_),
    .S(_286_),
    .Y(_100_)
  );
  MUX2X1 _628_ (
    .A(_194_),
    .B(_217_),
    .S(_286_),
    .Y(_101_)
  );
  MUX2X1 _629_ (
    .A(_196_),
    .B(_218_),
    .S(_286_),
    .Y(_102_)
  );
  MUX2X1 _630_ (
    .A(_198_),
    .B(_219_),
    .S(_286_),
    .Y(_103_)
  );
  MUX2X1 _631_ (
    .A(_200_),
    .B(_220_),
    .S(_286_),
    .Y(_104_)
  );
  MUX2X1 _632_ (
    .A(_202_),
    .B(_221_),
    .S(_286_),
    .Y(_105_)
  );
  NAND2X1 _633_ (
    .A(_387_),
    .B(_405_),
    .Y(_287_)
  );
  OR2X1 _634_ (
    .A(_388_),
    .B(_287_),
    .Y(_288_)
  );
  OAI21X1 _635_ (
    .A(_388_),
    .B(_287_),
    .C(_339_),
    .Y(_289_)
  );
  OAI21X1 _636_ (
    .A(_206_),
    .B(_288_),
    .C(_289_),
    .Y(_106_)
  );
  OAI21X1 _637_ (
    .A(_388_),
    .B(_287_),
    .C(_346_),
    .Y(_290_)
  );
  OAI21X1 _638_ (
    .A(_207_),
    .B(_288_),
    .C(_290_),
    .Y(_107_)
  );
  OAI21X1 _639_ (
    .A(_388_),
    .B(_287_),
    .C(_347_),
    .Y(_291_)
  );
  OAI21X1 _640_ (
    .A(_208_),
    .B(_288_),
    .C(_291_),
    .Y(_108_)
  );
  OAI21X1 _641_ (
    .A(_388_),
    .B(_287_),
    .C(_348_),
    .Y(_292_)
  );
  OAI21X1 _642_ (
    .A(_209_),
    .B(_288_),
    .C(_292_),
    .Y(_109_)
  );
  OAI21X1 _643_ (
    .A(_388_),
    .B(_287_),
    .C(_349_),
    .Y(_293_)
  );
  OAI21X1 _644_ (
    .A(_210_),
    .B(_288_),
    .C(_293_),
    .Y(_110_)
  );
  OAI21X1 _645_ (
    .A(_388_),
    .B(_287_),
    .C(_350_),
    .Y(_294_)
  );
  OAI21X1 _646_ (
    .A(_211_),
    .B(_288_),
    .C(_294_),
    .Y(_111_)
  );
  OAI21X1 _647_ (
    .A(_388_),
    .B(_287_),
    .C(_351_),
    .Y(_295_)
  );
  OAI21X1 _648_ (
    .A(_212_),
    .B(_288_),
    .C(_295_),
    .Y(_112_)
  );
  OAI21X1 _649_ (
    .A(_388_),
    .B(_287_),
    .C(_352_),
    .Y(_296_)
  );
  OAI21X1 _650_ (
    .A(_213_),
    .B(_288_),
    .C(_296_),
    .Y(_113_)
  );
  OAI21X1 _651_ (
    .A(_388_),
    .B(_287_),
    .C(_353_),
    .Y(_297_)
  );
  OAI21X1 _652_ (
    .A(_214_),
    .B(_288_),
    .C(_297_),
    .Y(_114_)
  );
  OAI21X1 _653_ (
    .A(_388_),
    .B(_287_),
    .C(_354_),
    .Y(_298_)
  );
  OAI21X1 _654_ (
    .A(_215_),
    .B(_288_),
    .C(_298_),
    .Y(_115_)
  );
  OAI21X1 _655_ (
    .A(_388_),
    .B(_287_),
    .C(_340_),
    .Y(_299_)
  );
  OAI21X1 _656_ (
    .A(_216_),
    .B(_288_),
    .C(_299_),
    .Y(_116_)
  );
  OAI21X1 _657_ (
    .A(_388_),
    .B(_287_),
    .C(_341_),
    .Y(_300_)
  );
  OAI21X1 _658_ (
    .A(_217_),
    .B(_288_),
    .C(_300_),
    .Y(_117_)
  );
  OAI21X1 _659_ (
    .A(_388_),
    .B(_287_),
    .C(_342_),
    .Y(_301_)
  );
  OAI21X1 _660_ (
    .A(_218_),
    .B(_288_),
    .C(_301_),
    .Y(_118_)
  );
  OAI21X1 _661_ (
    .A(_388_),
    .B(_287_),
    .C(_343_),
    .Y(_302_)
  );
  OAI21X1 _662_ (
    .A(_219_),
    .B(_288_),
    .C(_302_),
    .Y(_119_)
  );
  OAI21X1 _663_ (
    .A(_388_),
    .B(_287_),
    .C(_344_),
    .Y(_303_)
  );
  OAI21X1 _664_ (
    .A(_220_),
    .B(_288_),
    .C(_303_),
    .Y(_120_)
  );
  OAI21X1 _665_ (
    .A(_388_),
    .B(_287_),
    .C(_345_),
    .Y(_304_)
  );
  OAI21X1 _666_ (
    .A(_221_),
    .B(_288_),
    .C(_304_),
    .Y(_121_)
  );
  NAND3X1 _667_ (
    .A(_388_),
    .B(_205_),
    .C(_405_),
    .Y(_305_)
  );
  MUX2X1 _668_ (
    .A(_173_),
    .B(_206_),
    .S(_305_),
    .Y(_122_)
  );
  MUX2X1 _669_ (
    .A(_175_),
    .B(_207_),
    .S(_305_),
    .Y(_123_)
  );
  MUX2X1 _670_ (
    .A(_177_),
    .B(_208_),
    .S(_305_),
    .Y(_124_)
  );
  MUX2X1 _671_ (
    .A(_179_),
    .B(_209_),
    .S(_305_),
    .Y(_125_)
  );
  MUX2X1 _672_ (
    .A(_181_),
    .B(_210_),
    .S(_305_),
    .Y(_126_)
  );
  MUX2X1 _673_ (
    .A(_183_),
    .B(_211_),
    .S(_305_),
    .Y(_127_)
  );
  MUX2X1 _674_ (
    .A(_185_),
    .B(_212_),
    .S(_305_),
    .Y(_128_)
  );
  MUX2X1 _675_ (
    .A(_187_),
    .B(_213_),
    .S(_305_),
    .Y(_129_)
  );
  MUX2X1 _676_ (
    .A(_189_),
    .B(_214_),
    .S(_305_),
    .Y(_130_)
  );
  MUX2X1 _677_ (
    .A(_191_),
    .B(_215_),
    .S(_305_),
    .Y(_131_)
  );
  MUX2X1 _678_ (
    .A(_193_),
    .B(_216_),
    .S(_305_),
    .Y(_132_)
  );
  MUX2X1 _679_ (
    .A(_195_),
    .B(_217_),
    .S(_305_),
    .Y(_133_)
  );
  MUX2X1 _680_ (
    .A(_197_),
    .B(_218_),
    .S(_305_),
    .Y(_134_)
  );
  MUX2X1 _681_ (
    .A(_199_),
    .B(_219_),
    .S(_305_),
    .Y(_135_)
  );
  MUX2X1 _682_ (
    .A(_201_),
    .B(_220_),
    .S(_305_),
    .Y(_136_)
  );
  MUX2X1 _683_ (
    .A(_203_),
    .B(_221_),
    .S(_305_),
    .Y(_137_)
  );
  NAND3X1 _684_ (
    .A(_388_),
    .B(_387_),
    .C(_405_),
    .Y(_306_)
  );
  MUX2X1 _685_ (
    .A(_371_),
    .B(_389_),
    .S(_306_),
    .Y(_307_)
  );
  INVX1 _686_ (
    .A(_307_),
    .Y(_138_)
  );
  MUX2X1 _687_ (
    .A(_378_),
    .B(_396_),
    .S(_306_),
    .Y(_308_)
  );
  INVX1 _688_ (
    .A(_308_),
    .Y(_139_)
  );
  MUX2X1 _689_ (
    .A(_379_),
    .B(_397_),
    .S(_306_),
    .Y(_309_)
  );
  INVX1 _690_ (
    .A(_309_),
    .Y(_140_)
  );
  MUX2X1 _691_ (
    .A(_380_),
    .B(_398_),
    .S(_306_),
    .Y(_310_)
  );
  INVX1 _692_ (
    .A(_310_),
    .Y(_141_)
  );
  MUX2X1 _693_ (
    .A(_381_),
    .B(_399_),
    .S(_306_),
    .Y(_311_)
  );
  INVX1 _694_ (
    .A(_311_),
    .Y(_142_)
  );
  MUX2X1 _695_ (
    .A(_382_),
    .B(_400_),
    .S(_306_),
    .Y(_312_)
  );
  INVX1 _696_ (
    .A(_312_),
    .Y(_143_)
  );
  MUX2X1 _697_ (
    .A(_383_),
    .B(_401_),
    .S(_306_),
    .Y(_313_)
  );
  INVX1 _698_ (
    .A(_313_),
    .Y(_144_)
  );
  MUX2X1 _699_ (
    .A(_384_),
    .B(_402_),
    .S(_306_),
    .Y(_314_)
  );
  INVX1 _700_ (
    .A(_314_),
    .Y(_145_)
  );
  MUX2X1 _701_ (
    .A(_385_),
    .B(_403_),
    .S(_306_),
    .Y(_315_)
  );
  INVX1 _702_ (
    .A(_315_),
    .Y(_146_)
  );
  MUX2X1 _703_ (
    .A(_386_),
    .B(_404_),
    .S(_306_),
    .Y(_316_)
  );
  INVX1 _704_ (
    .A(_316_),
    .Y(_147_)
  );
  MUX2X1 _705_ (
    .A(_372_),
    .B(_390_),
    .S(_306_),
    .Y(_317_)
  );
  INVX1 _706_ (
    .A(_317_),
    .Y(_148_)
  );
  MUX2X1 _707_ (
    .A(_373_),
    .B(_391_),
    .S(_306_),
    .Y(_318_)
  );
  INVX1 _708_ (
    .A(_318_),
    .Y(_149_)
  );
  MUX2X1 _709_ (
    .A(_374_),
    .B(_392_),
    .S(_306_),
    .Y(_319_)
  );
  INVX1 _710_ (
    .A(_319_),
    .Y(_150_)
  );
  MUX2X1 _711_ (
    .A(_375_),
    .B(_393_),
    .S(_306_),
    .Y(_320_)
  );
  INVX1 _712_ (
    .A(_320_),
    .Y(_151_)
  );
  MUX2X1 _713_ (
    .A(_376_),
    .B(_394_),
    .S(_306_),
    .Y(_321_)
  );
  INVX1 _714_ (
    .A(_321_),
    .Y(_152_)
  );
  MUX2X1 _715_ (
    .A(_377_),
    .B(_395_),
    .S(_306_),
    .Y(_322_)
  );
  INVX1 _716_ (
    .A(_322_),
    .Y(_153_)
  );
  DFFPOSX1 _717_ (
    .CLK(clk),
    .D(_406_),
    .Q(\regar[0] [0])
  );
  DFFPOSX1 _718_ (
    .CLK(clk),
    .D(_407_),
    .Q(\regar[0] [1])
  );
  DFFPOSX1 _719_ (
    .CLK(clk),
    .D(_408_),
    .Q(\regar[0] [2])
  );
  DFFPOSX1 _720_ (
    .CLK(clk),
    .D(_409_),
    .Q(\regar[0] [3])
  );
  DFFPOSX1 _721_ (
    .CLK(clk),
    .D(_410_),
    .Q(\regar[0] [4])
  );
  DFFPOSX1 _722_ (
    .CLK(clk),
    .D(_411_),
    .Q(\regar[0] [5])
  );
  DFFPOSX1 _723_ (
    .CLK(clk),
    .D(_412_),
    .Q(\regar[0] [6])
  );
  DFFPOSX1 _724_ (
    .CLK(clk),
    .D(_413_),
    .Q(\regar[0] [7])
  );
  DFFPOSX1 _725_ (
    .CLK(clk),
    .D(_414_),
    .Q(\regar[0] [8])
  );
  DFFPOSX1 _726_ (
    .CLK(clk),
    .D(_415_),
    .Q(\regar[0] [9])
  );
  DFFPOSX1 _727_ (
    .CLK(clk),
    .D(_416_),
    .Q(\regar[0] [10])
  );
  DFFPOSX1 _728_ (
    .CLK(clk),
    .D(_417_),
    .Q(\regar[0] [11])
  );
  DFFPOSX1 _729_ (
    .CLK(clk),
    .D(_418_),
    .Q(\regar[0] [12])
  );
  DFFPOSX1 _730_ (
    .CLK(clk),
    .D(_419_),
    .Q(\regar[0] [13])
  );
  DFFPOSX1 _731_ (
    .CLK(clk),
    .D(_420_),
    .Q(\regar[0] [14])
  );
  DFFPOSX1 _732_ (
    .CLK(clk),
    .D(_421_),
    .Q(\regar[0] [15])
  );
  DFFPOSX1 _733_ (
    .CLK(clk),
    .D(_422_),
    .Q(\regar[1] [0])
  );
  DFFPOSX1 _734_ (
    .CLK(clk),
    .D(_423_),
    .Q(\regar[1] [1])
  );
  DFFPOSX1 _735_ (
    .CLK(clk),
    .D(_424_),
    .Q(\regar[1] [2])
  );
  DFFPOSX1 _736_ (
    .CLK(clk),
    .D(_425_),
    .Q(\regar[1] [3])
  );
  DFFPOSX1 _737_ (
    .CLK(clk),
    .D(_426_),
    .Q(\regar[1] [4])
  );
  DFFPOSX1 _738_ (
    .CLK(clk),
    .D(_427_),
    .Q(\regar[1] [5])
  );
  DFFPOSX1 _739_ (
    .CLK(clk),
    .D(_428_),
    .Q(\regar[1] [6])
  );
  DFFPOSX1 _740_ (
    .CLK(clk),
    .D(_429_),
    .Q(\regar[1] [7])
  );
  DFFPOSX1 _741_ (
    .CLK(clk),
    .D(_430_),
    .Q(\regar[1] [8])
  );
  DFFPOSX1 _742_ (
    .CLK(clk),
    .D(_431_),
    .Q(\regar[1] [9])
  );
  DFFPOSX1 _743_ (
    .CLK(clk),
    .D(_432_),
    .Q(\regar[1] [10])
  );
  DFFPOSX1 _744_ (
    .CLK(clk),
    .D(_433_),
    .Q(\regar[1] [11])
  );
  DFFPOSX1 _745_ (
    .CLK(clk),
    .D(_434_),
    .Q(\regar[1] [12])
  );
  DFFPOSX1 _746_ (
    .CLK(clk),
    .D(_435_),
    .Q(\regar[1] [13])
  );
  DFFPOSX1 _747_ (
    .CLK(clk),
    .D(_436_),
    .Q(\regar[1] [14])
  );
  DFFPOSX1 _748_ (
    .CLK(clk),
    .D(_437_),
    .Q(\regar[1] [15])
  );
  DFFPOSX1 _749_ (
    .CLK(clk),
    .D(_438_),
    .Q(\regar[2] [0])
  );
  DFFPOSX1 _750_ (
    .CLK(clk),
    .D(_439_),
    .Q(\regar[2] [1])
  );
  DFFPOSX1 _751_ (
    .CLK(clk),
    .D(_440_),
    .Q(\regar[2] [2])
  );
  DFFPOSX1 _752_ (
    .CLK(clk),
    .D(_441_),
    .Q(\regar[2] [3])
  );
  DFFPOSX1 _753_ (
    .CLK(clk),
    .D(_442_),
    .Q(\regar[2] [4])
  );
  DFFPOSX1 _754_ (
    .CLK(clk),
    .D(_443_),
    .Q(\regar[2] [5])
  );
  DFFPOSX1 _755_ (
    .CLK(clk),
    .D(_444_),
    .Q(\regar[2] [6])
  );
  DFFPOSX1 _756_ (
    .CLK(clk),
    .D(_445_),
    .Q(\regar[2] [7])
  );
  DFFPOSX1 _757_ (
    .CLK(clk),
    .D(_446_),
    .Q(\regar[2] [8])
  );
  DFFPOSX1 _758_ (
    .CLK(clk),
    .D(_447_),
    .Q(\regar[2] [9])
  );
  DFFPOSX1 _759_ (
    .CLK(clk),
    .D(_448_),
    .Q(\regar[2] [10])
  );
  DFFPOSX1 _760_ (
    .CLK(clk),
    .D(_449_),
    .Q(\regar[2] [11])
  );
  DFFPOSX1 _761_ (
    .CLK(clk),
    .D(_450_),
    .Q(\regar[2] [12])
  );
  DFFPOSX1 _762_ (
    .CLK(clk),
    .D(_451_),
    .Q(\regar[2] [13])
  );
  DFFPOSX1 _763_ (
    .CLK(clk),
    .D(_452_),
    .Q(\regar[2] [14])
  );
  DFFPOSX1 _764_ (
    .CLK(clk),
    .D(_453_),
    .Q(\regar[2] [15])
  );
  DFFPOSX1 _765_ (
    .CLK(clk),
    .D(_454_),
    .Q(\regar[3] [0])
  );
  DFFPOSX1 _766_ (
    .CLK(clk),
    .D(_455_),
    .Q(\regar[3] [1])
  );
  DFFPOSX1 _767_ (
    .CLK(clk),
    .D(_456_),
    .Q(\regar[3] [2])
  );
  DFFPOSX1 _768_ (
    .CLK(clk),
    .D(_457_),
    .Q(\regar[3] [3])
  );
  DFFPOSX1 _769_ (
    .CLK(clk),
    .D(_458_),
    .Q(\regar[3] [4])
  );
  DFFPOSX1 _770_ (
    .CLK(clk),
    .D(_459_),
    .Q(\regar[3] [5])
  );
  DFFPOSX1 _771_ (
    .CLK(clk),
    .D(_460_),
    .Q(\regar[3] [6])
  );
  DFFPOSX1 _772_ (
    .CLK(clk),
    .D(_461_),
    .Q(\regar[3] [7])
  );
  DFFPOSX1 _773_ (
    .CLK(clk),
    .D(_462_),
    .Q(\regar[3] [8])
  );
  DFFPOSX1 _774_ (
    .CLK(clk),
    .D(_463_),
    .Q(\regar[3] [9])
  );
  DFFPOSX1 _775_ (
    .CLK(clk),
    .D(_464_),
    .Q(\regar[3] [10])
  );
  DFFPOSX1 _776_ (
    .CLK(clk),
    .D(_465_),
    .Q(\regar[3] [11])
  );
  DFFPOSX1 _777_ (
    .CLK(clk),
    .D(_466_),
    .Q(\regar[3] [12])
  );
  DFFPOSX1 _778_ (
    .CLK(clk),
    .D(_467_),
    .Q(\regar[3] [13])
  );
  DFFPOSX1 _779_ (
    .CLK(clk),
    .D(_468_),
    .Q(\regar[3] [14])
  );
  DFFPOSX1 _780_ (
    .CLK(clk),
    .D(_469_),
    .Q(\regar[3] [15])
  );
  assign _323_ = \regar[0] [0];
  assign _339_ = \regar[1] [0];
  assign _170_ = brad[0];
  assign _355_ = \regar[2] [0];
  assign _371_ = \regar[3] [0];
  assign _171_ = brad[1];
  assign b[0] = _154_;
  assign _330_ = \regar[0] [1];
  assign _346_ = \regar[1] [1];
  assign _362_ = \regar[2] [1];
  assign _378_ = \regar[3] [1];
  assign b[1] = _161_;
  assign _331_ = \regar[0] [2];
  assign _347_ = \regar[1] [2];
  assign _363_ = \regar[2] [2];
  assign _379_ = \regar[3] [2];
  assign b[2] = _162_;
  assign _332_ = \regar[0] [3];
  assign _348_ = \regar[1] [3];
  assign _364_ = \regar[2] [3];
  assign _380_ = \regar[3] [3];
  assign b[3] = _163_;
  assign _333_ = \regar[0] [4];
  assign _349_ = \regar[1] [4];
  assign _365_ = \regar[2] [4];
  assign _381_ = \regar[3] [4];
  assign b[4] = _164_;
  assign _334_ = \regar[0] [5];
  assign _350_ = \regar[1] [5];
  assign _366_ = \regar[2] [5];
  assign _382_ = \regar[3] [5];
  assign b[5] = _165_;
  assign _335_ = \regar[0] [6];
  assign _351_ = \regar[1] [6];
  assign _367_ = \regar[2] [6];
  assign _383_ = \regar[3] [6];
  assign b[6] = _166_;
  assign _336_ = \regar[0] [7];
  assign _352_ = \regar[1] [7];
  assign _368_ = \regar[2] [7];
  assign _384_ = \regar[3] [7];
  assign b[7] = _167_;
  assign _337_ = \regar[0] [8];
  assign _353_ = \regar[1] [8];
  assign _369_ = \regar[2] [8];
  assign _385_ = \regar[3] [8];
  assign b[8] = _168_;
  assign _338_ = \regar[0] [9];
  assign _354_ = \regar[1] [9];
  assign _370_ = \regar[2] [9];
  assign _386_ = \regar[3] [9];
  assign b[9] = _169_;
  assign _324_ = \regar[0] [10];
  assign _340_ = \regar[1] [10];
  assign _356_ = \regar[2] [10];
  assign _372_ = \regar[3] [10];
  assign b[10] = _155_;
  assign _325_ = \regar[0] [11];
  assign _341_ = \regar[1] [11];
  assign _357_ = \regar[2] [11];
  assign _373_ = \regar[3] [11];
  assign b[11] = _156_;
  assign _326_ = \regar[0] [12];
  assign _342_ = \regar[1] [12];
  assign _358_ = \regar[2] [12];
  assign _374_ = \regar[3] [12];
  assign b[12] = _157_;
  assign _327_ = \regar[0] [13];
  assign _343_ = \regar[1] [13];
  assign _359_ = \regar[2] [13];
  assign _375_ = \regar[3] [13];
  assign b[13] = _158_;
  assign _328_ = \regar[0] [14];
  assign _344_ = \regar[1] [14];
  assign _360_ = \regar[2] [14];
  assign _376_ = \regar[3] [14];
  assign b[14] = _159_;
  assign _329_ = \regar[0] [15];
  assign _345_ = \regar[1] [15];
  assign _361_ = \regar[2] [15];
  assign _377_ = \regar[3] [15];
  assign b[15] = _160_;
  assign _088_ = arad[0];
  assign _089_ = arad[1];
  assign a[0] = _072_;
  assign a[1] = _079_;
  assign a[2] = _080_;
  assign a[3] = _081_;
  assign a[4] = _082_;
  assign a[5] = _083_;
  assign a[6] = _084_;
  assign a[7] = _085_;
  assign a[8] = _086_;
  assign a[9] = _087_;
  assign a[10] = _073_;
  assign a[11] = _074_;
  assign a[12] = _075_;
  assign a[13] = _076_;
  assign a[14] = _077_;
  assign a[15] = _078_;
  assign _388_ = wad[1];
  assign _387_ = wad[0];
  assign _405_ = we;
  assign _389_ = wd[0];
  assign _406_ = _090_;
  assign _396_ = wd[1];
  assign _407_ = _091_;
  assign _397_ = wd[2];
  assign _408_ = _092_;
  assign _398_ = wd[3];
  assign _409_ = _093_;
  assign _399_ = wd[4];
  assign _410_ = _094_;
  assign _400_ = wd[5];
  assign _411_ = _095_;
  assign _401_ = wd[6];
  assign _412_ = _096_;
  assign _402_ = wd[7];
  assign _413_ = _097_;
  assign _403_ = wd[8];
  assign _414_ = _098_;
  assign _404_ = wd[9];
  assign _415_ = _099_;
  assign _390_ = wd[10];
  assign _416_ = _100_;
  assign _391_ = wd[11];
  assign _417_ = _101_;
  assign _392_ = wd[12];
  assign _418_ = _102_;
  assign _393_ = wd[13];
  assign _419_ = _103_;
  assign _394_ = wd[14];
  assign _420_ = _104_;
  assign _395_ = wd[15];
  assign _421_ = _105_;
  assign _422_ = _106_;
  assign _423_ = _107_;
  assign _424_ = _108_;
  assign _425_ = _109_;
  assign _426_ = _110_;
  assign _427_ = _111_;
  assign _428_ = _112_;
  assign _429_ = _113_;
  assign _430_ = _114_;
  assign _431_ = _115_;
  assign _432_ = _116_;
  assign _433_ = _117_;
  assign _434_ = _118_;
  assign _435_ = _119_;
  assign _436_ = _120_;
  assign _437_ = _121_;
  assign _438_ = _122_;
  assign _439_ = _123_;
  assign _440_ = _124_;
  assign _441_ = _125_;
  assign _442_ = _126_;
  assign _443_ = _127_;
  assign _444_ = _128_;
  assign _445_ = _129_;
  assign _446_ = _130_;
  assign _447_ = _131_;
  assign _448_ = _132_;
  assign _449_ = _133_;
  assign _450_ = _134_;
  assign _451_ = _135_;
  assign _452_ = _136_;
  assign _453_ = _137_;
  assign _454_ = _138_;
  assign _455_ = _139_;
  assign _456_ = _140_;
  assign _457_ = _141_;
  assign _458_ = _142_;
  assign _459_ = _143_;
  assign _460_ = _144_;
  assign _461_ = _145_;
  assign _462_ = _146_;
  assign _463_ = _147_;
  assign _464_ = _148_;
  assign _465_ = _149_;
  assign _466_ = _150_;
  assign _467_ = _151_;
  assign _468_ = _152_;
  assign _469_ = _153_;
endmodule

(* top =  1  *)
(* src = "top.sv:1.1-13.10" *)
module top(we, wd, clk, rst);
  (* src = "top.sv:2.18-2.19" *)
  wire [15:0] a;
  (* src = "top.sv:3.17-3.21" *)
  wire [1:0] arad;
  (* src = "top.sv:2.20-2.21" *)
  wire [15:0] b;
  (* src = "top.sv:3.22-3.26" *)
  wire [1:0] brad;
  (* src = "top.sv:1.53-1.56" *)
  input clk;
  wire clk;
  (* src = "top.sv:10.11-10.12" *)
  wire h;
  (* src = "top.sv:6.18-6.19" *)
  wire [10:0] o;
  (* src = "top.sv:4.17-4.19" *)
  wire [2:0] op;
  (* src = "top.sv:5.17-5.20" *)
  wire [5:0] pca;
  (* src = "top.sv:1.58-1.61" *)
  input rst;
  wire rst;
  (* src = "top.sv:3.27-3.30" *)
  wire [1:0] wad;
  (* src = "top.sv:1.43-1.45" *)
  output [15:0] wd;
  wire [15:0] wd;
  (* src = "top.sv:1.19-1.21" *)
  output we;
  wire we;
  (* module_not_derived = 32'd1 *)
  (* src = "top.sv:9.9-9.23" *)
  alu alu (
    .a(a),
    .b(b),
    .op(op),
    .r(wd)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.sv:12.6-12.40" *)
  dec dec (
    .aradr(arad),
    .bradr(brad),
    .halt(h),
    .o(o),
    .op(op),
    .wadr(wad),
    .we(we)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.sv:11.10-11.21" *)
  imem imem (
    .o(o),
    .pc(pca)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.sv:10.8-10.25" *)
  pc pc (
    .clk(clk),
    .halt(h),
    .pc(pca),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.sv:8.10-8.47" *)
  rega rega (
    .a(a),
    .arad(arad),
    .b(b),
    .brad(brad),
    .clk(clk),
    .rst(rst),
    .wad(wad),
    .wd(wd),
    .we(we)
  );
endmodule
