/* Generated by Yosys 0.29 (git sha1 9c5a60eb201, clang 14.0.3 -fPIC -Os) */

(* top =  1  *)
(* src = "venmac.sv:1.1-25.10" *)
module venmac(a, b, c, can, coin, clk, rst);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  (* src = "venmac.sv:2.11-2.12" *)
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  (* src = "venmac.sv:2.13-2.14" *)
  wire _025_;
  (* src = "venmac.sv:4.29-4.30" *)
  wire _026_;
  (* src = "venmac.sv:4.29-4.30" *)
  wire _027_;
  (* src = "venmac.sv:4.29-4.30" *)
  wire _028_;
  (* src = "venmac.sv:4.29-4.30" *)
  wire _029_;
  (* src = "venmac.sv:3.18-3.21" *)
  wire _030_;
  (* src = "venmac.sv:4.24-4.28" *)
  wire _031_;
  (* src = "venmac.sv:4.24-4.28" *)
  wire _032_;
  (* src = "venmac.sv:4.24-4.28" *)
  wire _033_;
  (* src = "venmac.sv:4.24-4.28" *)
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  (* src = "venmac.sv:2.19-2.22" *)
  wire _063_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  (* src = "venmac.sv:2.11-2.12" *)
  input a;
  wire a;
  (* src = "venmac.sv:2.13-2.14" *)
  input b;
  wire b;
  (* src = "venmac.sv:4.29-4.30" *)
  output [3:0] c;
  wire [3:0] c;
  (* src = "venmac.sv:3.18-3.21" *)
  output can;
  wire can;
  (* src = "venmac.sv:2.15-2.18" *)
  input clk;
  wire clk;
  (* src = "venmac.sv:4.24-4.28" *)
  output [3:0] coin;
  wire [3:0] coin;
  (* src = "venmac.sv:2.19-2.22" *)
  input rst;
  wire rst;
  INVX1 _069_ (
    .A(_027_),
    .Y(_035_)
  );
  INVX1 _070_ (
    .A(_029_),
    .Y(_036_)
  );
  INVX1 _071_ (
    .A(_025_),
    .Y(_037_)
  );
  INVX1 _072_ (
    .A(_063_),
    .Y(_038_)
  );
  OR2X1 _073_ (
    .A(_027_),
    .B(_026_),
    .Y(_039_)
  );
  AND2X1 _074_ (
    .A(_028_),
    .B(_039_),
    .Y(_040_)
  );
  NOR2X1 _075_ (
    .A(_029_),
    .B(_040_),
    .Y(_041_)
  );
  INVX1 _076_ (
    .A(_041_),
    .Y(_030_)
  );
  NOR2X1 _077_ (
    .A(_026_),
    .B(_041_),
    .Y(_031_)
  );
  NAND2X1 _078_ (
    .A(_027_),
    .B(_026_),
    .Y(_042_)
  );
  AOI21X1 _079_ (
    .A(_039_),
    .B(_042_),
    .C(_041_),
    .Y(_032_)
  );
  OAI21X1 _080_ (
    .A(_028_),
    .B(_039_),
    .C(_029_),
    .Y(_043_)
  );
  NOR2X1 _081_ (
    .A(_040_),
    .B(_043_),
    .Y(_033_)
  );
  AND2X1 _082_ (
    .A(_029_),
    .B(_040_),
    .Y(_034_)
  );
  AND2X1 _083_ (
    .A(_026_),
    .B(_020_),
    .Y(_044_)
  );
  NAND2X1 _084_ (
    .A(_026_),
    .B(_020_),
    .Y(_045_)
  );
  NOR2X1 _085_ (
    .A(_026_),
    .B(_020_),
    .Y(_046_)
  );
  OR2X1 _086_ (
    .A(_026_),
    .B(_020_),
    .Y(_047_)
  );
  NOR2X1 _087_ (
    .A(_044_),
    .B(_046_),
    .Y(_048_)
  );
  OAI21X1 _088_ (
    .A(_025_),
    .B(_048_),
    .C(_038_),
    .Y(_049_)
  );
  AOI21X1 _089_ (
    .A(_025_),
    .B(_048_),
    .C(_049_),
    .Y(_021_)
  );
  AOI21X1 _090_ (
    .A(_025_),
    .B(_047_),
    .C(_044_),
    .Y(_050_)
  );
  OAI21X1 _091_ (
    .A(_037_),
    .B(_046_),
    .C(_045_),
    .Y(_051_)
  );
  OAI21X1 _092_ (
    .A(_027_),
    .B(_051_),
    .C(_038_),
    .Y(_052_)
  );
  AOI21X1 _093_ (
    .A(_027_),
    .B(_051_),
    .C(_052_),
    .Y(_022_)
  );
  AND2X1 _094_ (
    .A(_028_),
    .B(_025_),
    .Y(_053_)
  );
  NAND2X1 _095_ (
    .A(_028_),
    .B(_025_),
    .Y(_054_)
  );
  XNOR2X1 _096_ (
    .A(_028_),
    .B(_025_),
    .Y(_055_)
  );
  INVX1 _097_ (
    .A(_055_),
    .Y(_056_)
  );
  NOR3X1 _098_ (
    .A(_035_),
    .B(_050_),
    .C(_055_),
    .Y(_057_)
  );
  NAND3X1 _099_ (
    .A(_027_),
    .B(_051_),
    .C(_056_),
    .Y(_058_)
  );
  OAI21X1 _100_ (
    .A(_035_),
    .B(_050_),
    .C(_055_),
    .Y(_059_)
  );
  NAND2X1 _101_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  NOR2X1 _102_ (
    .A(_063_),
    .B(_060_),
    .Y(_023_)
  );
  NOR3X1 _103_ (
    .A(_029_),
    .B(_053_),
    .C(_057_),
    .Y(_061_)
  );
  AOI21X1 _104_ (
    .A(_054_),
    .B(_058_),
    .C(_036_),
    .Y(_062_)
  );
  NOR3X1 _105_ (
    .A(_063_),
    .B(_061_),
    .C(_062_),
    .Y(_024_)
  );
  (* src = "venmac.sv:6.5-12.8" *)
  DFFPOSX1 _106_ (
    .CLK(clk),
    .D(_065_),
    .Q(c[0])
  );
  (* src = "venmac.sv:6.5-12.8" *)
  DFFPOSX1 _107_ (
    .CLK(clk),
    .D(_066_),
    .Q(c[1])
  );
  (* src = "venmac.sv:6.5-12.8" *)
  DFFPOSX1 _108_ (
    .CLK(clk),
    .D(_067_),
    .Q(c[2])
  );
  (* src = "venmac.sv:6.5-12.8" *)
  DFFPOSX1 _109_ (
    .CLK(clk),
    .D(_068_),
    .Q(c[3])
  );
  assign _027_ = c[1];
  assign _028_ = c[2];
  assign _029_ = c[3];
  assign _026_ = c[0];
  assign can = _030_;
  assign coin[0] = _031_;
  assign coin[1] = _032_;
  assign coin[2] = _033_;
  assign coin[3] = _034_;
  assign _020_ = a;
  assign _025_ = b;
  assign _063_ = rst;
  assign _065_ = _021_;
  assign _066_ = _022_;
  assign _067_ = _023_;
  assign _068_ = _024_;
endmodule
