/* Generated by Yosys 0.29 (git sha1 9c5a60eb201, clang 14.0.3 -fPIC -Os) */

(* top =  1  *)
(* src = "venmac.sv:1.1-25.10" *)
module venmac(a, b, c, can, coin, clk, rst);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _20_;
  (* src = "venmac.sv:2.11-2.12" *)
  input a;
  wire a;
  (* src = "venmac.sv:2.13-2.14" *)
  input b;
  wire b;
  (* src = "venmac.sv:4.29-4.30" *)
  output [3:0] c;
  reg [3:0] c;
  (* src = "venmac.sv:3.18-3.21" *)
  output can;
  wire can;
  (* src = "venmac.sv:2.15-2.18" *)
  input clk;
  wire clk;
  (* src = "venmac.sv:4.24-4.28" *)
  output [3:0] coin;
  wire [3:0] coin;
  (* src = "venmac.sv:2.19-2.22" *)
  input rst;
  wire rst;
  assign _00_ = c[1] & c[2];
  assign _01_ = _00_ | c[3];
  assign _02_ = c[0] & ~(c[1]);
  assign _03_ = c[3] | ~(c[2]);
  assign _04_ = _02_ & ~(_03_);
  assign can = _04_ | _01_;
  assign coin[0] = can & ~(c[0]);
  assign _05_ = c[1] ^ c[0];
  assign coin[1] = can & ~(_05_);
  assign _06_ = ~(c[1] | c[0]);
  assign _07_ = _06_ ^ c[2];
  assign coin[2] = can & ~(_07_);
  assign _08_ = c[2] & ~(_06_);
  assign _09_ = _08_ ^ c[3];
  assign coin[3] = can & ~(_09_);
  assign _10_ = ~(a ^ c[0]);
  assign _20_[0] = ~(_10_ ^ b);
  assign _11_ = ~c[1];
  assign _12_ = ~(a & c[0]);
  assign _13_ = b & ~(_10_);
  assign _14_ = _12_ & ~(_13_);
  assign _20_[1] = _14_ ^ _11_;
  assign _15_ = b ^ c[2];
  assign _16_ = _14_ | _11_;
  assign _20_[2] = ~(_16_ ^ _15_);
  assign _17_ = ~(b & c[2]);
  assign _18_ = _15_ & ~(_16_);
  assign _19_ = _18_ | ~(_17_);
  assign _20_[3] = _19_ ^ c[3];
  (* \always_ff  = 32'd1 *)
  (* src = "venmac.sv:6.5-12.8" *)
  always @(posedge clk)
    if (rst) c[0] <= 1'h0;
    else c[0] <= _20_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "venmac.sv:6.5-12.8" *)
  always @(posedge clk)
    if (rst) c[1] <= 1'h0;
    else c[1] <= _20_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "venmac.sv:6.5-12.8" *)
  always @(posedge clk)
    if (rst) c[2] <= 1'h0;
    else c[2] <= _20_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "venmac.sv:6.5-12.8" *)
  always @(posedge clk)
    if (rst) c[3] <= 1'h0;
    else c[3] <= _20_[3];
endmodule
