/* Generated by Yosys 0.29 (git sha1 9c5a60eb201, clang 14.0.3 -fPIC -Os) */

(* top =  1  *)
(* src = "venmac.sv:1.1-66.10" *)
module venmac(a, b, can, coin, clk, rst);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  (* src = "venmac.sv:2.11-2.12" *)
  input a;
  wire a;
  (* src = "venmac.sv:2.13-2.14" *)
  input b;
  wire b;
  (* src = "venmac.sv:3.18-3.21" *)
  output can;
  wire can;
  (* src = "venmac.sv:2.15-2.18" *)
  input clk;
  wire clk;
  (* src = "venmac.sv:4.24-4.28" *)
  output [3:0] coin;
  wire [3:0] coin;
  (* src = "venmac.sv:2.19-2.22" *)
  input rst;
  wire rst;
  (* onehot = 32'd1 *)
  (* unused_bits = "1 4 6 9" *)
  wire [9:0] state;
  assign _06_ = ~rst;
  assign _07_ = b & ~(a);
  assign _08_ = _06_ & ~(_07_);
  assign _09_ = b | ~(a);
  assign _10_ = ~(_09_ & _08_);
  assign _11_ = state[3] & ~(_10_);
  assign _12_ = _09_ | rst;
  assign _13_ = state[5] & ~(_12_);
  assign _02_ = _13_ | _11_;
  assign _14_ = state[5] & ~(_10_);
  assign _15_ = state[0] & ~(_12_);
  assign _03_ = _15_ | _14_;
  assign _16_ = state[3] & ~(_12_);
  assign _17_ = state[8] & ~(_10_);
  assign _05_ = _17_ | _16_;
  assign _18_ = state[2] & ~(_10_);
  assign _19_ = state[8] & ~(_12_);
  assign _01_ = _19_ | _18_;
  assign _20_ = state[7] | state[2];
  assign _21_ = _20_ & ~(_12_);
  assign _22_ = ~(_07_ & _06_);
  assign _23_ = state[0] & ~(_22_);
  assign _24_ = _23_ | _21_;
  assign _25_ = state[7] & ~(_10_);
  assign _04_ = _25_ | _24_;
  assign _26_ = state[0] & ~(_10_);
  assign _00_ = _26_ | rst;
  assign _27_ = ~(state[8] | state[5]);
  assign _28_ = ~(state[8] | state[2]);
  assign _29_ = state[5] | state[3];
  assign _30_ = _28_ & ~(_29_);
  assign _31_ = _30_ | _27_;
  assign coin[0] = _07_ & ~(_31_);
  assign _32_ = ~(state[8] | state[3]);
  assign _33_ = _32_ | _30_;
  assign coin[1] = _07_ & ~(_33_);
  assign _34_ = _30_ | ~(state[2]);
  assign coin[2] = _07_ & ~(_34_);
  assign _35_ = state[3] | state[2];
  assign _36_ = _27_ & ~(_35_);
  assign _37_ = _07_ & ~(_36_);
  assign _38_ = state[7] & ~(_09_);
  assign _39_ = _38_ | _37_;
  assign _40_ = _09_ & ~(_07_);
  assign can = _39_ & ~(_40_);
  reg \state_reg[0] ;
  always @(posedge clk)
    \state_reg[0]  <= _00_;
  assign state[0] = \state_reg[0] ;
  reg \state_reg[2] ;
  always @(posedge clk)
    \state_reg[2]  <= _01_;
  assign state[2] = \state_reg[2] ;
  reg \state_reg[3] ;
  always @(posedge clk)
    \state_reg[3]  <= _02_;
  assign state[3] = \state_reg[3] ;
  reg \state_reg[5] ;
  always @(posedge clk)
    \state_reg[5]  <= _03_;
  assign state[5] = \state_reg[5] ;
  reg \state_reg[7] ;
  always @(posedge clk)
    \state_reg[7]  <= _04_;
  assign state[7] = \state_reg[7] ;
  reg \state_reg[8] ;
  always @(posedge clk)
    \state_reg[8]  <= _05_;
  assign state[8] = \state_reg[8] ;
  assign coin[3] = 1'h0;
endmodule
