/* Generated by Yosys 0.29 (git sha1 9c5a60eb201, clang 14.0.3 -fPIC -Os) */

(* top =  1  *)
(* src = "chika.sv:2.1-37.10" *)
module ex(a, b, clk, rst);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "chika.sv:3.11-3.12" *)
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "chika.sv:4.18-4.19" *)
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "chika.sv:6.11-6.14" *)
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "chika.sv:3.11-3.12" *)
  input a;
  wire a;
  (* src = "chika.sv:4.18-4.19" *)
  output b;
  wire b;
  (* src = "chika.sv:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "chika.sv:6.11-6.14" *)
  input rst;
  wire rst;
  (* onehot = 32'd1 *)
  wire [2:0] s;
  INVX1 _24_ (
    .A(_23_),
    .Y(_15_)
  );
  INVX1 _25_ (
    .A(_21_),
    .Y(_16_)
  );
  AOI21X1 _26_ (
    .A(_10_),
    .B(_22_),
    .C(_20_),
    .Y(_17_)
  );
  NAND2X1 _27_ (
    .A(_15_),
    .B(_17_),
    .Y(_13_)
  );
  AOI21X1 _28_ (
    .A(_10_),
    .B(_23_),
    .C(_21_),
    .Y(_18_)
  );
  INVX1 _29_ (
    .A(_18_),
    .Y(_14_)
  );
  NOR2X1 _30_ (
    .A(_20_),
    .B(_16_),
    .Y(_11_)
  );
  NOR2X1 _31_ (
    .A(_20_),
    .B(_10_),
    .Y(_19_)
  );
  AND2X1 _32_ (
    .A(_22_),
    .B(_19_),
    .Y(_12_)
  );
  DFFPOSX1 _33_ (
    .CLK(clk),
    .D(_02_),
    .Q(s[0])
  );
  DFFPOSX1 _34_ (
    .CLK(clk),
    .D(_00_),
    .Q(s[1])
  );
  DFFPOSX1 _35_ (
    .CLK(clk),
    .D(_01_),
    .Q(s[2])
  );
  assign _20_ = rst;
  assign _10_ = a;
  assign _22_ = s[1];
  assign _02_ = _13_;
  assign _23_ = s[2];
  assign _21_ = s[0];
  assign b = _14_;
  assign _00_ = _11_;
  assign _01_ = _12_;
endmodule
