/* Generated by Yosys 0.29 (git sha1 9c5a60eb201, clang 14.0.3 -fPIC -Os) */

(* top =  1  *)
(* src = "ex.sv:1.1-35.10" *)
module ex(a, b, clk, rst);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "ex.sv:2.11-2.12" *)
  input a;
  wire a;
  (* src = "ex.sv:3.18-3.19" *)
  output b;
  wire b;
  (* src = "ex.sv:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "ex.sv:5.11-5.14" *)
  input rst;
  wire rst;
  (* onehot = 32'd1 *)
  reg [2:0] s;
  assign _03_ = s[2] | rst;
  assign _04_ = rst | ~(a);
  assign _05_ = s[1] & ~(_04_);
  assign _02_ = _05_ | _03_;
  assign _06_ = s[2] & a;
  assign _07_ = _06_ | s[0];
  assign _08_ = ~(s[0] | s[2]);
  assign b = _07_ & ~(_08_);
  assign _00_ = s[0] & ~(rst);
  assign _09_ = rst | a;
  assign _01_ = s[1] & ~(_09_);
  always @(posedge clk)
    s[0] <= _02_;
  always @(posedge clk)
    s[1] <= _00_;
  always @(posedge clk)
    s[2] <= _01_;
endmodule
